import type { Metadata } from 'next'
import { Vazirmatn } from 'next/font/google'
import './globals.css'

import { ConfigProvider } from 'antd';
import ToastProvider from './provider/ToastProvider';
import AuthProvider from './provider/AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const vazir = Vazirmatn({ 
  subsets: ['arabic'],
  weight: "600",
  variable: "--font-vazir"
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir='rtl'>
      <body className={`${vazir.variable} font-vazir`}>
        <AuthProvider>
          <ConfigProvider
            theme={{
              token: {
                // Seed Token
                colorPrimary: '#5727A3',
                borderRadius: 2,
        
              },
            }}
          >
            <ToastProvider />
            {children}
          </ConfigProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
